In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
data_train = np.array([[0, 1],
                       [1, 0],
                       [0, 0],
                       [1, 1]])
label_train = np.array([0, 0, 0, 1])[:,None]

In [3]:
and_graph = tf.Graph()
num_hidden_neuron = 2
with and_graph.as_default():
    train_input = tf.constant(data_train, dtype=tf.float64)
    train_label = tf.constant(label_train, dtype=tf.float64)
    
    # hidden layer
    weight_hidden = tf.Variable(2*tf.random_uniform((2, num_hidden_neuron), dtype=tf.float64)-1)
    bias_hidden = tf.Variable(tf.random_uniform((num_hidden_neuron,), dtype=tf.float64))
    layer_hidden = tf.matmul(train_input, weight_hidden) + bias_hidden
    activation_hidden = tf.sigmoid(layer_hidden)
    
    # output layer
    weight_out = tf.Variable(2*tf.random_uniform((num_hidden_neuron, 1), dtype=tf.float64)-1)
    bias_out = tf.Variable(tf.random_uniform((1,), dtype=tf.float64))
    layer_out = tf.matmul(activation_hidden, weight_out) + bias_out
    output = tf.sigmoid(layer_out)
    
    # loss
    loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(layer_out, train_label))
    
    # optimizer
    optimizer = tf.train.GradientDescentOptimizer(2.0).minimize(loss)

In [5]:
num_iter = 1000
with tf.Session(graph=and_graph) as session:
    tf.global_variables_initializer().run()
    print("Initialize all variables")
    
    for i in range(num_iter):
        _, l, weight_h, b_h, weight_o, b_o, out = session.run([optimizer, loss, 
                                                               weight_hidden, bias_hidden,
                                                               weight_out, bias_out,
                                                               output])
        
        if (i+1) % 100 == 0:
            print("iteration {}: {}".format(i+1, l))

Initialize all variables
iteration 100: 0.057754679068
iteration 200: 0.0187826588709
iteration 300: 0.010501316327
iteration 400: 0.00713907679709
iteration 500: 0.0053562367854
iteration 600: 0.0042630356871
iteration 700: 0.00352855956371
iteration 800: 0.00300312527185
iteration 900: 0.00260963353126
iteration 1000: 0.00230450564107


In [6]:
out

array([[  1.72241909e-03],
       [  1.67208144e-03],
       [  7.03881503e-05],
       [  9.94266254e-01]])

In [7]:
weight_h

array([[-2.86219512, -4.66395069],
       [-2.99103929, -4.56567359]])

In [8]:
weight_o

array([[ -5.57279534],
       [-10.43150362]])

In [9]:
b_h

array([ 3.65404026,  6.37951627])

In [10]:
b_o

array([ 6.28344314])

In [11]:
and_graph = tf.Graph()
num_hidden_neuron = 2
with and_graph.as_default():
    train_input = tf.constant(data_train, dtype=tf.float64)
    train_label = tf.constant(label_train, dtype=tf.float64)
    
    # hidden layer
    weight_hidden = tf.Variable(2*tf.random_uniform((2, num_hidden_neuron), dtype=tf.float64)-1)
    bias_hidden = tf.Variable(tf.random_uniform((num_hidden_neuron,), dtype=tf.float64))
    layer_hidden = tf.matmul(train_input, weight_hidden) + bias_hidden
    activation_hidden = tf.sigmoid(layer_hidden)
    
    # output layer
    weight_out = tf.Variable(2*tf.random_uniform((num_hidden_neuron, 1), dtype=tf.float64)-1)
    bias_out = tf.Variable(tf.random_uniform((1,), dtype=tf.float64))
    layer_out = tf.matmul(activation_hidden, weight_out) + bias_out
    output = tf.sigmoid(layer_out)
    
    # loss (l2 norm)
    loss = tf.nn.l2_loss(output - train_label)
    
    # optimizer
    optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

In [12]:
num_iter = 1000
with tf.Session(graph=and_graph) as session:
    tf.global_variables_initializer().run()
    print("Initialize all variables")
    
    for i in range(num_iter):
        _, l, weight_h, b_h, weight_o, b_o, out = session.run([optimizer, loss, 
                                                               weight_hidden, bias_hidden,
                                                               weight_out, bias_out,
                                                               output])
        
        if (i+1) % 100 == 0:
            print("iteration {}: {}".format(i+1, l))

Initialize all variables
iteration 100: 0.259293215858
iteration 200: 0.120622652535
iteration 300: 0.0495504772375
iteration 400: 0.0258149905831
iteration 500: 0.0162681048305
iteration 600: 0.0115070630647
iteration 700: 0.00875426266972
iteration 800: 0.00699432113063
iteration 900: 0.005786159643
iteration 1000: 0.00491206679844


In [13]:
out

array([[ 0.04558156],
       [ 0.04828239],
       [ 0.00865698],
       [ 0.92692248]])